config/routes.rb
BrigadeMvp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :apps

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/app.rb
class App < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/_form.html.haml
= form_for @app, {:class => "form-horizontal"} do |f|
  -if @app.errors.any?
    #error_explanation
      %h2= "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
      %ul
        - @app.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :name, {:class => "control-label"}
    .controls
      = f.text_field :name
  .control-group
    = f.label :tag_line
    .controls
      = f.text_field :tag_line
  .control-group
    = f.label :description
    .controls
      = f.text_area :description, {:class => "span8"}
  .control-group
    = f.label :instructions
    .controls
      = f.text_area :instructions, {:class => "span8"}
  .control-group
    = f.label :github_url
    .controls
      = f.text_field :github_url
  .control-group
    = f.label :demo_url
    .controls
      = f.text_field :demo_url
  .control-group
    = f.label :cfa_project_url
    .controls
      = f.text_field :cfa_project_url
  .control-group
    = f.label :deployments
    .controls
      = f.text_field :deployments
  .form-actions
    = f.submit 'Save', {:class => "btn-primary"}

app/views/apps/edit.html.haml
%h1 Editing app

= render 'form'

= link_to 'Show', @app
\|
= link_to 'Back', apps_path

app/views/apps/index.html.haml
%h1 Applications
%br
%table.table.table-bordered
  %tr
    %th Name
    %th Description
    %th

  - @apps.each do |app|
    %tr
      %td= app.name
      %td= app.tag_line
      %td= link_to 'Show', app

%br

- if user_signed_in?
  = link_to 'New App', new_app_path

app/views/apps/new.html.haml
%h1 New app

= render 'form'

= link_to 'Back', apps_path

app/views/apps/show.html.haml
%p#notice= notice

%h2
  = @app.name
%br
%p
  %b Tag line:
  = @app.tag_line
%p
  %b Description:
  = @app.description
%p
  %b Instructions:
  = @app.instructions
%p
  %b Github url:
  = link_to @app.github_url, @app.github_url, :target => "_blank"
%p
  %b Demo url:
  = link_to @app.demo_url, @app.demo_url, :target => "_blank"
%p
  %b Code for America project:
  = link_to @app.cfa_project_url, @app.cfa_project_url, :target => "_blank"
%p
  %b Deployments:
  = @app.deployments

- if user_signed_in?
  = link_to 'Edit', edit_app_path(@app)
  \|
= link_to 'Back', apps_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title BrigadeMvp
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    #header.wrap
      %a#logo.like-btn{:href => "/"} Code for America
      #tag-line
        %h1 THE CFA BRIGADE:
        %h2 BUILDING THE NEW CIVIC INFRASTUCTURE
      #social
        %li
          %a#rss{:href => "http://codeforamerica.org/feed/"} RSS
        %li
          %a#fb{:href => "http://www.facebook.com/codeforamerica"}Facebook
        %li
          %a#yt{:href => "http://www.youtube.com/user/CodeforAmerica"}YouTube
        %li
          %a#tw{:href => "http://www.twitter.com/codeforamerica"} Twitter
        %li
          %a#mail{:href => "mailto:info@codeforamerica.org"}E-mail
      #nav-wrap
        %ul#nav.menu
          %li
            = link_to 'Home', root_path
          %li
            = link_to 'Applications', apps_path
    %br
    .wrap-t
      #become-wrap.wrap.clearfix
        = yield

    #footer
      .wrap

app/views/welcome/index.html.haml
%h1 Code for America Brigade : Building the new civic Infrastructure
%br
%h2
  ABOUT THE BRIGADE

%p The Code for America Brigade is an organizing force for a growing community of civic minded developers, designers, data scientists, and community leaders who will contribute their talents towards addressing the problems we see everday. The technology that we’ll develop together and deploy locally will form a new Civic Web.

%h2 Web Platform

%ul
  %li
  An online portal to connect individuals with local projects and collaborators and to stand up and maintain civic applications.
  %li
  Project pages for civic apps with comprehensive technical documentation and strategies for implementation.

%br
%h2 Community Engagement

%ul
  %li
    Brigade teams use events and local area networks to increase adoption and sustainability of open source civic technology.
  %li
    Code for America develops corporate, government, and non-profit partnerships that create a pipeline of resources and professional development opportunities for each node in the Brigade network.

%br
%h3
  GOALS FOR YEAR-END
  %ul
    %li
      20 Apps
    %li
      50 Cities
    %li
      100 Volunteers/Members
    %li
      500 Users

%br
%h3
  STARTUP TIMELINE

%ul
  %li
    JANUARY: Find Civic Apps
  %li
    FEBUARY: Opensource Apps
  %li
    FEBUARY: Alpha Events
  %li
  MARCH: Portal Launch

%h2
  DEPLOY AN APP. HELP BUILD THE CIVIC WEB.